#!/usr/bin/env python3
"""Generate media/identifiers/oui.js from the IEEE MAC address registries.

WHY THIS EXISTS
---------------
Bluetooth company IDs (company_identifiers.js) name the *advertiser*. They say
nothing about a device whose manufacturer data is proprietary or absent — the
scan CSV that prompted this was full of "Unknown (0x3A4D)" rows, and 0x3A4D is
not an assigned company ID at all. What those devices do have is a MAC address,
and 48:CA:43 is registered to Espressif.

So this ships the IEEE assignment registries:

  MA-L  24-bit prefix, "48CA43"     ~39k assignments
  MA-M  28-bit prefix, "48CA43A"    smaller blocks
  MA-S  36-bit prefix, "48CA43ABC"  smallest blocks

The app does longest-prefix-first matching (MA-S, then MA-M, then MA-L) because
a single MA-L block can be subdivided among many MA-S holders.

IMPORTANT — this only ever applies to *public* Bluetooth addresses. Most BLE
devices advertise a randomised address, where these bytes are noise; naming a
vendor from one would be actively misleading. Registry.ouiVendor() enforces
that, and this file carries no addresses of its own.

Output is deliberately one entry per line so the app can parse it with the same
line scanner as the other registries.

    python tools/build-oui-registry.py

Then re-run tools/build-registry-index.py to refresh the hashes.
"""

from __future__ import annotations

import csv
import io
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "media" / "identifiers" / "oui.js"

# (url, expected hex-prefix length) — longest first is handled app-side.
SOURCES = [
    ("https://standards-oui.ieee.org/oui/oui.csv", 6),
    ("https://standards-oui.ieee.org/oui28/mam.csv", 7),
    ("https://standards-oui.ieee.org/oui36/oui36.csv", 9),
]

# Names that identify nothing. IEEE keeps assignments whose holder asked to be
# withheld, and a row reading "Private" is worse than no row: it looks like a
# lookup succeeded.
USELESS = {"private", "n/a", "none", "unknown", ""}


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "ghosttooth-registry-build"})
    with urllib.request.urlopen(req, timeout=180) as resp:  # noqa: S310 - fixed IEEE URLs
        return resp.read().decode("utf-8", errors="replace")


def clean(name: str) -> str:
    # Collapse whitespace and strip the quotes/control characters that would
    # break the one-entry-per-line format the app parses.
    out = " ".join(name.split())
    return out.replace('"', "'").replace("\\", "")


def main() -> int:
    entries: dict[str, str] = {}
    counts = []

    for url, width in SOURCES:
        try:
            text = fetch(url)
        except Exception as exc:  # noqa: BLE001 - report and carry on
            print(f"  !! {url}: {exc}", file=sys.stderr)
            return 1

        n = 0
        for row in csv.DictReader(io.StringIO(text)):
            prefix = (row.get("Assignment") or "").strip().upper()
            org = clean(row.get("Organization Name") or "")
            if len(prefix) != width or not all(c in "0123456789ABCDEF" for c in prefix):
                continue
            if org.lower() in USELESS:
                continue
            # A multicast or locally-administered first octet is never a real
            # assignment; if one appears, the row is corrupt.
            first = int(prefix[:2], 16)
            if first & 0x03:
                continue
            entries[prefix] = org
            n += 1
        counts.append((url.rsplit("/", 1)[-1], n))
        print(f"  {url.rsplit('/', 1)[-1]:12} {n:6,} assignments")

    if not entries:
        print("no entries parsed", file=sys.stderr)
        return 1

    vendors = sorted({v for v in entries.values()})
    index = {name: i for i, name in enumerate(vendors)}

    lines = [
        "/* GHOSTTOOTH — IEEE MAC address assignments (MA-L / MA-M / MA-S).",
        " * Generated by tools/build-oui-registry.py. Do not hand-edit.",
        " *",
        " * Only meaningful for PUBLIC Bluetooth addresses. A randomised address",
        " * carries no vendor, and the app must not look one up for it.",
        " *",
        " * GHOSTTOOTH_OUI_VENDORS is the name table; GHOSTTOOTH_OUI maps each",
        " * assignment prefix to an index in it, which keeps the file about a",
        f" * third of the size ({len(vendors):,} names for {len(entries):,} prefixes).",
        " */",
        "window.GHOSTTOOTH_OUI_VENDORS = [",
    ]
    lines += [f'"{name}",' for name in vendors]
    lines.append("];")
    lines.append("window.GHOSTTOOTH_OUI = [")
    lines += [f'["{p}",{index[entries[p]]}],' for p in sorted(entries)]
    lines.append("];")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    # LF endings: the index hashes these bytes and GitHub Pages serves LF, so a
    # CRLF write here would make every integrity check fail on device.
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    print(f"\nwrote {OUT.relative_to(ROOT)}")
    print(f"  prefixes {len(entries):,}   vendors {len(vendors):,}   {OUT.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
